[mypy]
python_version = 3.11
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
no_implicit_optional = True
strict_equality = True

[mypy-duckdb.*]
ignore_missing_imports = True

[mypy-click.*]
ignore_missing_imports = True

[mypy-tabulate.*]
ignore_missing_imports = True

[mypy-yaml.*]
ignore_missing_imports = True

[mypy-pytest.*]
ignore_missing_imports = True
