"""Report generator: produce markdown reports from metric diffs.

Outputs:
- PR comment markdown (for GitHub Actions)
- Full diff report (for CI artifacts)
- Summary badge data (pass/fail/warning counts)
"""

from datetime import UTC, datetime
from typing import Any

from tabulate import tabulate

from .diff import DriftSeverity, MetricDiff, summarize_diffs

SEVERITY_EMOJI: dict[DriftSeverity, str] = {
    DriftSeverity.CRITICAL: "🔴",
    DriftSeverity.WARNING: "🟡",
    DriftSeverity.INFO: "🔵",
    DriftSeverity.NEW: "🟢",
    DriftSeverity.REMOVED: "⚫",
    DriftSeverity.NONE: "✅",
}


def _format_pct_change(pct: float | None) -> str:
    """Format a percentage change for display, or 'N/A' if None."""
    if pct is not None:
        return f"{pct * 100:+.1f}%"
    return "N/A"


def _format_value(value: float | None) -> str:
    """Format a metric value for display, or '-' if None."""
    if value is not None:
        return f"{value:.2f}"
    return "-"


_TABLE_HEADERS: list[str] = ["", "Metric", "Period", "Baseline", "Current", "Change"]


def _diff_to_table_row(d: MetricDiff) -> list[str]:
    """Convert a MetricDiff to a table row for markdown output."""
    emoji = SEVERITY_EMOJI[d.severity]
    dim_str = f" [{d.dimension_name}={d.dimension_value}]" if d.dimension_name else ""
    return [
        emoji,
        f"`{d.metric_name}`{dim_str}",
        d.period[:10] if d.period else "",
        _format_value(d.baseline_value),
        _format_value(d.current_value),
        _format_pct_change(d.pct_change),
    ]


def _build_significant_section(diffs: list[MetricDiff]) -> list[str]:
    """Build the 'Significant Changes' section for critical/warning diffs."""
    significant = [d for d in diffs if d.severity in (DriftSeverity.CRITICAL, DriftSeverity.WARNING)]
    if not significant:
        return []
    lines = ["### Significant Changes", ""]
    table_data = [_diff_to_table_row(d) for d in significant]
    lines.append(tabulate(table_data, headers=_TABLE_HEADERS, tablefmt="github"))
    lines.append("")
    return lines


def _build_details_section(diffs: list[MetricDiff]) -> list[str]:
    """Build the collapsible full-details section."""
    lines = ["<details>", "<summary>Full metric diff (click to expand)</summary>", ""]
    all_table = [_diff_to_table_row(d) for d in diffs if d.severity != DriftSeverity.NONE]
    if all_table:
        lines.append(tabulate(all_table, headers=_TABLE_HEADERS, tablefmt="github"))
    else:
        lines.append("No changes detected.")
    lines.extend(["", "</details>", "", "---"])
    lines.append("*Generated by [semantic-ci](https://github.com/zahar-t/metric-trust-pipeline)*")
    return lines


def generate_pr_comment(
    diffs: list[MetricDiff],
    baseline_run_id: str,
    current_run_id: str,
    baseline_label: str | None = None,
    current_label: str | None = None,
) -> str:
    """Generate a concise markdown PR comment summarizing metric diffs.

    Designed to be posted as a GitHub PR comment via GitHub Actions.
    Shows only meaningful changes (warning+critical) in the summary,
    with a collapsible details section for all metrics.
    """
    summary: dict[str, Any] = summarize_diffs(diffs)
    now = datetime.now(UTC).strftime("%Y-%m-%d %H:%M UTC")

    header = "## Semantic CI: Metrics Check Passed" if summary["pass"] else "## Semantic CI: Metrics Check Failed"
    baseline_display = baseline_label or baseline_run_id
    current_display = current_label or current_run_id

    lines: list[str] = [
        header,
        "",
        f"**Baseline**: `{baseline_display}` -> **Current**: `{current_display}`",
        f"**Run at**: {now}",
        "",
        "### Summary",
        "",
        "| Status | Count |",
        "|--------|-------|",
        f"| Critical | {summary['critical']} |",
        f"| Warning | {summary['warning']} |",
        f"| Info | {summary['info']} |",
        f"| New | {summary['new']} |",
        f"| Removed | {summary['removed']} |",
        f"| Unchanged | {summary['unchanged']} |",
        "",
    ]

    lines.extend(_build_significant_section(diffs))
    lines.extend(_build_details_section(diffs))

    return "\n".join(lines)


def generate_full_report(
    diffs: list[MetricDiff],
    baseline_run_id: str,
    current_run_id: str,
) -> str:
    """Generate a detailed report suitable for CI artifact storage."""
    summary: dict[str, Any] = summarize_diffs(diffs)
    now = datetime.now(UTC).isoformat()
    result_str = "PASS" if summary["pass"] else "FAIL"

    lines: list[str] = [
        "# Semantic CI -- Full Metric Diff Report",
        "",
        f"Generated: {now}",
        f"Baseline run: {baseline_run_id}",
        f"Current run: {current_run_id}",
        f"Total metrics compared: {summary['total_metrics']}",
        f"Result: **{result_str}**",
        "",
        "---",
        "",
    ]

    # Group by metric name
    by_metric: dict[str, list[MetricDiff]] = {}
    for d in diffs:
        by_metric.setdefault(d.metric_name, []).append(d)

    for metric_name, metric_diffs in sorted(by_metric.items()):
        has_issues = any(d.severity in (DriftSeverity.CRITICAL, DriftSeverity.WARNING) for d in metric_diffs)
        icon = "[FAIL]" if has_issues else "[OK]"
        lines.append(f"## {icon} {metric_name}")
        lines.append("")

        for d in metric_diffs:
            if d.severity == DriftSeverity.NONE:
                continue
            dim_str = f" ({d.dimension_name}={d.dimension_value})" if d.dimension_name else ""
            lines.append(f"- {SEVERITY_EMOJI[d.severity]} **{d.period[:10]}**{dim_str}: {d.explanation}")

        lines.append("")

    return "\n".join(lines)
